### ISSUE TITLE
有办法调用玩客云api，还更新吗？

### ISSUE THREAD

**Issue by mackyzhan** [aiqinxuancai/WkyFast#9]
玩客云api监听的是8800端口，在局域网调用api需要解决签名问题，但是ssh登陆玩客云后curl调用api则不会校验签名，我在玩客云上装了个端口转发工具，局域网就可以直接调用玩客云api，绕过签名验证，这样可以做局域网的app了。

比如：
/sysmgr?sign=&req_time=&req_type=1&userid=123&opt=getuploaddir

返回
{
	"rtn": 0,
	"paths": ["\/media\/sda5\/onecloud", "\/media\/sda5\/onecloud\/tddownload", "\/media\/sda5\/onecloud\/mobilebackup", "\/media\/sda5\/onecloud\/sdbackup", "\/media\/sda5\/onecloud\/cloud", "\/media\/sda5\/onecloud\/.private"],
	"disk_sn": 97465,
	"partition_id": 5,
	"partition_path": "\/media\/sda5"
}

/sysmgr?opt=getsmbscandir
返回：
{"all_disk":0,"paths":["/media/sda5/onecloud/otc_shared"],"rtn":0}

/fmgr?sign=&req_time=&req_type=1&userid=123&opt=querydir&path=/media/sda5/onecloud/otc_shared
返回：
{
	"rtn": 0,
	"path": "/media/sda5/onecloud/otc_shared",
	"filelist": [{
		"name": "other",
		"attribute": "0x01",
		"size": "4096",
		"time": "1710678108",
		"cid": "",
		"gcid": "",
		"property": "0x00"
	},, {
		"name": "影视",
		"attribute": "0x01",
		"size": "0",
		"time": "1709466140",
		"cid": "",
		"gcid": "",
		"property": "0x00"
	}]
}

**Comment by aiqinxuancai** [comment]
666，但是我不打算继续更新这个项目了，就算目前api能用，高速通道后续也可能被封。
最近用畅网的方案组了台Unraid，使用Aria2也挺舒服的，甚至很多资源下载速度远超玩客云。可以看一下我在这个项目基础上开发的Aria2Fast。

**Comment by mackyzhan** [comment]
真遗憾。我也在玩客云上装了aria2代替了迅雷，装了百度云cli同步百度盘，不过缺少SMB和文件管理工具，看来得自己搞了。
